### PR TITLE
Adding SourceMaps

### PR DESCRIPTION
**Pull request by john-Graham**
Adding a few lines to generate sourceMaps for CSS

### CODE REVIEW

**Comment by bdukes** [comment]
You'll need to run `yarn add --dev gulp-sourcemaps` to register the dependency in the `package.json` and `yarn.lock` files.  

And then, I believe you need to call `sourcemaps.init()` before you change the files (e.g. right after `gulp.src`) and `sourcemaps.write('.')` after you're done changing the files (e.g. right before `gulp.dest`).

Hope it helps!

**Comment by nvisionative** [comment]
Thanks for the PR @john-Graham.  And thanks @bdukes for the guidance.  @john-Graham once you update, let us know and we'll review.

**Comment by tksheppard** [comment]
gulp-sourcemaps is already registered as a dependency in the package.json and yarn.lock. It was something I knew we wanted to implement.

**Comment by tksheppard** [comment]
Looks great! Thank you @john-Graham for your contribution! And @bdukes for your guidance!

**Comment by john-Graham** [comment]
Anytime.  and thanks... Noob to this.

**Pull request merged**
