### PR TITLE
Register all skin objects

### PR DESCRIPTION
**Pull request by bdukes**
This adds every `ascx` file in `~/admin/Skins`

There may be a conflict between the `DnnJsInclude`, `DnnCssExclude`, etc. skin objects and the `DotNetNuke.Web.Client.ClientResourceManagement` register (I'd bet you can just remove that one, but I'm developing blind at the conference now :smile:)

Also, there are some skin objects here that are definitely outdated, but I thought I'd start with all of them, and then we could discuss which ones should never be used (e.g. `solpartmenu`)

### CODE REVIEW

**Comment by tksheppard** [comment]
I tested this out and their are indeed problems with the `DnnJsInclude/Exclude`, `DnnCssInclude/Exclude` skins objects. I even removed the `DotNetNuke.Web.Client.ClientResourceManagement` and it still caused issues. I will have to delve further into this.

Another issue was the `solpartmenu` was missing from my admin folder as of version 9.1.1, was this on an earlier 9.x version? The rest were golden. 

Thanks for the contribution!

**Comment by bdukes** [comment]
That `solpartmenu` item must have been left over from an upgrade.  Thanks for doing the investigative work @tksheppard!

**Comment by nvisionative** [comment]
@bdukes would you like to update your PR to remove the five skin objects `DnnJsInclude/Exclude`, `DnnCssInclude/Exclude` and `solpartmenu`?  Once that is complete, we'll merge the PR.  Thanks again!

**Comment by bdukes** [comment]
Sure thing, @nvisionative, I've now committed that change.  Thanks!

**Pull request merged**
